/*\
AUTHOR: Will Juntunen Cardinal Information Group 2-28-2016
EXEC dbo.refresh_inventory_FPIVTQUE
\*/
CREATE PROCEDURE [dbo].[refresh_inventory_FPIVTQUE_OLD]
AS
BEGIN
	SET NOCOUNT ON;



	/**********************
	TEST QUERIES
	DELETE FROM FPIVTQUE_HISTORY
	SELECT * FROM FPIVTQUE
	SELECT * FROM FPIVTQUE_HISTORY
	******************************/

	--- INSERT THE LIST OF CHANGED ITEMS, RECIEPTS AND ADJUSTMENTS.

	---INSERT [dbo].[FPIVTQUE]
	----SELECT * FROM TPS.ANDRXTST.CIGFTEST.FPIVTQUE --- GET THE LIST OF CHANGED ITEMS, RECIEPTS AND ADJUSTMENTS.

	-- Store new items into history
	insert into [foundation].[dbo].[FPIVTQUE_HISTORY] ( [inventory_message], [IVITM#], [IVWHSE], [version_time] )
	SELECT [inventory_message]
	,      [IVITM#]
	,      [IVWHSE]
	,      [version_time]
	FROM [foundation].[dbo].[FPIVTQUE]

	TRUNCATE TABLE dbo.FPIVTQUE; --- Truncate the local history table.

	INSERT dbo.FPIVTQUE ( IVITM#, IVWHSE )
	EXEC ('SELECT DISTINCT IVITM#, IVWHSE FROM CIGFTEST.FPIVTQUE WHERE IVWHSE <> 0') AT TPS;


	DELETE dbo.FPITMBRS
	FROM dbo.FPITMBRS AS REF
	JOIN dbo.FPIVTQUE AS V   ON REF.IRITEM = V.IVITM#
			AND REF.IRWHSE = V.IVWHSE; --- 7 ROWS

	INSERT INTO dbo.FPITMBRS ( IRITEM, IRWHSE, IRCTYP, IRQHRS, IRONLY, IRBYLM )
	EXEC('SELECT REF.IRITEM
	,      REF.IRWHSE
	,      REF.IRCTYP
	,      REF.IRQHRS
	,      REF.IRONLY
	,      REF.IRBYLM
	FROM FPITMBRS AS REF 
		JOIN CIGFTEST.FPIVTQUE AS V ON REF.IRITEM = V.IVITM# AND REF.IRWHSE = V.IVWHSE') AT TPS; 


	DELETE dbo.FPITMBAL
	FROM dbo.FPITMBAL AS REF
	JOIN dbo.FPIVTQUE AS V   ON REF.IBITEM = V.IVITM#
			AND REF.IBWHSE = V.IVWHSE; 


	INSERT INTO dbo.FPITMBAL ( IBITEM, IBWHSE, IBBUYR, IBBYRC, IBPICY, IBCULI, IBQHAW, IBQHAV, IBQHRS, IBQHSP, IBQMIP, IBQBAK, IBQONO, IBQTRI, IBQTRO, IBCMAV, IBCMRS, IBCMBK, IBTCMA, IBTCMR, IBQTRV, IBQCRV, IBQORV, IBQASC, IBSQOP, IBQOHB, IBQOHA, IBLRDT, IBNRDT, IBLSDT, IBLCDT, IBLPDT, IBLTDT, IBFPDT, IBFCDT, IBLIDT, IBINVT, IBFAST, IBAWC, [IBLFO$], IBLFOD, IBREOP, IBEOQ, IBABCC, IBSVCL, IBBUYF, IBSFST, IBPRDM, IBLSWP, IBLTDM, IBLTP, IBPRLT, IBABLD, IBLTLD, IBPDLD, IBRPLD, IBLSLD )
	EXEC('SELECT IBITEM
	,      IBWHSE
	,      IBBUYR
	,      IBBYRC
	,      IBPICY
	,      IBCULI
	,      IBQHAW
	,      IBQHAV
	,      IBQHRS
	,      IBQHSP
	,      IBQMIP
	,      IBQBAK
	,      IBQONO
	,      IBQTRI
	,      IBQTRO
	,      IBCMAV
	,      IBCMRS
	,      IBCMBK
	,      IBTCMA
	,      IBTCMR
	,      IBQTRV
	,      IBQCRV
	,      IBQORV
	,      IBQASC
	,      IBSQOP
	,      IBQOHB
	,      IBQOHA
	,      IBLRDT
	,      IBNRDT
	,      IBLSDT
	,      IBLCDT
	,      IBLPDT
	,      IBLTDT
	,      IBFPDT
	,      IBFCDT
	,      IBLIDT
	,      IBINVT
	,      IBFAST
	,      IBAWC
	,      IBLFO$
	,      IBLFOD
	,      IBREOP
	,      IBEOQ
	,      IBABCC
	,      IBSVCL
	,      IBBUYF
	,      IBSFST
	,      IBPRDM
	,      IBLSWP
	,      IBLTDM
	,      IBLTP
	,      IBPRLT
	,      IBABLD
	,      IBLTLD
	,      IBPDLD
	,      IBRPLD
	,      IBLSLD
	FROM FPITMBAL AS REF
	JOIN CIGFTEST.FPIVTQUE AS V   ON REF.IBITEM = V.IVITM#
			AND REF.IBWHSE = V.IVWHSE') AT TPS


	DELETE dbo.FPWHLDTL
	FROM dbo.FPWHLDTL AS REF
	JOIN dbo.FPIVTQUE AS V   ON REF.WDITEM = V.IVITM#
			AND REF.WDLOC = V.IVWHSE; --- 63 ROWS

	INSERT INTO dbo.FPWHLDTL ( WDLOC, WDZONE, WDAISL, WDBAY, WDTIER, WDBIN, WDITEM, WDDATE, WDTIME, WDQTYA, WDATYP, WDDSPY, WDOLOC, WDSTAT, WDUSET, WDRTYP, WDVNDN, WDPO#, WDLOT, WDEXPD, WDCRUP, WDVEXP )
	EXEC('SELECT WDLOC
	,      WDZONE
	,      WDAISL
	,      WDBAY
	,      WDTIER
	,      WDBIN
	,      WDITEM
	,      WDDATE
	,      WDTIME
	,      WDQTYA
	,      WDATYP
	,      WDDSPY
	,      WDOLOC
	,      WDSTAT
	,      WDUSET
	,      WDRTYP
	,      WDVNDN
	,      WDPO#
	,      WDLOT
	,      WDEXPD
	,      WDCRUP
	,      WDVEXP
	FROM FPWHLDTL AS REF
	JOIN CIGFTEST.FPIVTQUE AS V ON REF.WDITEM = V.IVITM#
			AND REF.WDLOC = V.IVWHSE') AT TPS;


	EXEC materialize_item_balances;
	EXEC ('DELETE FROM ANDRXTST.CIGFTEST.FPIVTQUE') AT TPS;

END